wsgi/odyssy/odyssy/settings.py
=> Updated settings.py for HTTPS. Fixes #9

wsgi/odyssy/odyssy/settings.py
=> Updated settings.py to include localhost as allowed host.

wsgi/odyssy/events/models.py, wsgi/odyssy/events/templates/events/event_list.html, wsgi/odyssy/events/templates/events/event_single_item.html
- Added HTML support
- Made place nullable
fixes #20 and #21
=> Fixed some bugs

wsgi/odyssy/events/models.py
fixes #24 . Change can be seen on new insertions, old data description will still show 'at'.
=> Event place issue fixed

wsgi/odyssy/announcement/models.py
=> Fixed bug announcement appearing after expiration

wsgi/odyssy/news/models.py
=> Fixed bug: News appear after they expire

wsgi/odyssy/announcement/models.py, wsgi/odyssy/basic/utils.py, wsgi/odyssy/news/models.py
=> Fixed bug #27

wsgi/odyssy/announcement/models.py, wsgi/odyssy/basic/utils.py, wsgi/odyssy/news/models.py
=> Fixed Bug: Consistent model structure

wsgi/odyssy/news/templates/news/single_news.html
=> Fixed bug: Bold tag having no effect in single_news.html

requirements.txt, wsgi/odyssy/announcement/models.py, wsgi/odyssy/announcement/templates/announcement/index.html, wsgi/odyssy/announcement/views.py, wsgi/odyssy/basic/admin.py, wsgi/odyssy/basic/models.py, wsgi/odyssy/basic/urls.py, wsgi/odyssy/basic/utils.py, wsgi/odyssy/events/views.py, wsgi/odyssy/news/models.py, wsgi/odyssy/news/views.py, wsgi/odyssy/odyssy/settings.py, wsgi/odyssy/odyssy/urls.py, wsgi/odyssy/tag/admin.py, wsgi/odyssy/tag/apps.py, wsgi/odyssy/tag/models.py, wsgi/odyssy/tag/templates/tag/announcement_tag.html, wsgi/odyssy/tag/templates/tag/news_tag.html, wsgi/odyssy/tag/templates/tag/picture_tag.html, wsgi/odyssy/tag/templates/tag/simple_tag.html, wsgi/odyssy/tag/tests.py, wsgi/odyssy/tag/urls.py, wsgi/odyssy/tag/views.py
Closes #15 
Also for using this we need to install django-taggit as a dependency and migrate first its database using `python manage.py migrate taggit`
=> Added tag app

wsgi/odyssy/announcement/views.py, wsgi/odyssy/basic/utils.py, wsgi/odyssy/events/views.py, wsgi/odyssy/news/views.py, wsgi/odyssy/tag/views.py
=> Fixed NoReverseMatch Error

wsgi/odyssy/basic/templates/basic/base.html
Fixes #54 
The script responsible for popovers has been corrected.
=> Fixed header anchor popovers

wsgi/odyssy/basic/templates/basic/index.html, wsgi/odyssy/basic/views.py
Replaced it with a temporary message
Fixed #57
=> Remove irelevant important announcement at index

wsgi/odyssy/basic/static/basic/css/style.css, wsgi/odyssy/basic/templates/basic/base.html, wsgi/odyssy/basic/templates/basic/index.html
=> Enable description of latest announcements, evets and news on homepage

.gitignore
=> Updated .gitignore for photologue cache

README.md
=> Updated README.md for mentioning makemigrations

wsgi/odyssy/odyssy/urls.py
=> Added photologue in project urls.py

wsgi/odyssy/basic/static/basic/css/style.css, wsgi/odyssy/basic/templates/basic/base.html
Fixes #55 
Public IP : http://13.126.164.61:8000
username: test
password: test
=> Remove social media footer links

wsgi/odyssy/announcement/templates/announcement/announcement-all.html, wsgi/odyssy/announcement/templates/announcement/info.html, wsgi/odyssy/basic/static/basic/css/style.css, wsgi/odyssy/basic/static/basic/js/main.js, wsgi/odyssy/basic/templates/basic/base.html, wsgi/odyssy/basic/templates/basic/index.html, wsgi/odyssy/events/templates/events/event_list.html, wsgi/odyssy/events/templates/events/event_single_item.html, wsgi/odyssy/news/templates/news/news_list.html, wsgi/odyssy/news/templates/news/single_news.html
Also referenced the issue #68.
Also improved some font styling.
Here are some Screenshots:
=> Added UI to Events, News, Announcements

wsgi/odyssy/people/views.py
=> Correct status typo of "staff"
